### ISSUE TITLE
Install-Package Error: Not compatible with '.NETFramework,Version=v4.7.1'?

### ISSUE THREAD

**Issue by CodeWarrior-Hawaii** [square/connect-csharp-sdk#104]
I am attempting to add this package via NuGet to an ASP.NET MVC web application targetting .NET Framework 4.7.1.  Install-Package responds with the following error message:

`Could not install package 'Square.Connect 2.14.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

.NET Framework 4.7.1 is compatible with .NET Standard 2.0 is it not?  I have not encountered this problem before and I am unsure as to how to proceed.

**Comment by StephenJosey** [comment]
@CodeWarrior-Hawaii what version of Visual Studio are you using? It appears that NetStandard 2.0 was added in Visual Studio 17 update 15.3. Can you please make sure you have a version 15.3 or greater and try again?

**Comment by CodeWarrior-Hawaii** [comment]
Aha!  Therein may lie the problem.  I am using VS 2017 15.2.

I'll give it an update and see what happens.

**Comment by CodeWarrior-Hawaii** [comment]
Alright!  That did it.  Thanks for the help, very muchly.
