### ISSUE TITLE
Could not install package 'Square.Connect 2.14.0' with Framework 4.6

### ISSUE THREAD

**Issue by gavin1970** [square/connect-csharp-sdk#105]
Is there not a .NETFramework version of this library?   I'm not running .NETStandard, but instead running Framework 4.6 and get the error during Nuget Install.   I had my fingers crossed as I have never written anything with .NETStandard and know little about it, but it was a no go...

Could not install package 'Square.Connect 2.14.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by gavin1970** [comment]
I just found that 4.71 has build in support for .NET Standard

https://github.com/dotnet/standard/issues/514

**Comment by gavin1970** [comment]
Also found that Square.Connect 2.10.1.297 supports Framework 4.5

**Comment by StephenJosey** [comment]
Yeah, for the latest version we use .NET Standard 2.0 which requires .NET Framework 4.6.1 or higher. See chart here from Microsoft: https://docs.microsoft.com/en-us/dotnet/standard/net-standard
