### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by jmawebtech** [square/connect-csharp-sdk#116]
Hi,

When your plugin returns the V1Payment created at field, is the timezone PST or UTC? If I query payments by date created, should I use UTC time or PST?

**Comment by StephenJosey** [comment]
All dates and times returned by our APIs are UTC: https://docs.connect.squareup.com/api/connect/v2#workingwithdates

You can offset the dates in a particular request to work with a particular timezone (see tech ref link above).
