### ISSUE TITLE
Response classes seem unnecessary

### ISSUE THREAD

**Issue by Alfetta159** [square/connect-csharp-sdk#130]
Most Response classes aggregate a specific response property and an error property where only one will be used. Why not simply return the response or throw an exception like the older endpoints do?

With the result/error response, it forces the user to either have to check for an error or risk creating a `NullReferenceException` which is far less helpful than the `ApiException`. And if the dev does check for an error, they might be able to handle it there, but if not, then they'll probably just throw an exception.

**Comment by StephenJosey** [comment]
Sorry for the delayed response here. I agree, the documentation is confusing. In REST calls, there is either `errors` or `locations`. I'm relaying this over to our SDK team to make sure it gets properly addressed.

**Comment by StephenJosey** [comment]
I'll close this issue for now. Please take a look at the new .NET SDK as this one is now deprecated.

**Comment by havenwood** [comment]
You can find the new Square .NET SDK in the [square/square-dotnet-sdk](https://github.com/square/square-dotnet-sdk) repo.
