### ISSUE TITLE
Customer Sort documentation needs updating

### ISSUE THREAD

**Issue by jiodice** [square/connect-csharp-sdk#138]
The link in the documentation to CustomerSortField goes nowhere
https://github.com/square/connect-csharp-sdk/blob/master/docs/CustomerSort.md

Also the content of this is blank:
https://github.com/square/connect-csharp-sdk/blob/master/docs/CustomerSortField.md

There used to be a Enum that I used in 2.14.0 but after updating to 2.23.0 it no longer exists so the following code no longer works:
string sortField = CustomerSortField.CREATEDAT.ToString();

The old enum value was "CREATEDAT = 1"

I was able to find the two string values in the Node.js documentation via Google search:
https://github.com/square/connect-nodejs-sdk/blob/master/docs/CustomerSortField.md

In the developer documentation you make it sound like there are a few different sorting options but besides default there is really only 1 option?
"It could be the total money spent at the merchant, the date of the first visit (etc)"

**Comment by StephenJosey** [comment]
Thanks for letting us know. We're taking a look at each of these and will follow up as soon as we have more info.

**Comment by StephenJosey** [comment]
Hey @jiodice so after speaking with the team, the [2.20.0 changelog](https://github.com/square/connect-csharp-sdk/blob/master/CHANGES.md#version-2200-2019-07-10) actually states:

> Breaking change — As of 2019-07-10 .NET Connect SDK does not support explicit ENUM types. Instead, the SDKs pass ENUM values as static Strings. Developer code can now choose to ignore unexpected String values when Square APIs return new values instead of being forced to throw runtime errors due to unexpected types. Additional information, including migration help, is available in the README.

However, you're right - the documentation needs to be updated to show the available strings that can be used. We're working on it.

**Comment by StephenJosey** [comment]
This was resolved in October, 2019. Closing out.
