### ISSUE TITLE
Deprecated class replacement

### ISSUE THREAD

**Issue by jmawebtech** [square/connect-csharp-sdk#147]
Hi,

I am upgrading from 2.18 to 2.25 and I get these errors:

warning CS0612: 'V1Item' is obsolete
warning CS0612: 'ListRefundsResponse' is obsolete
warning CS0612: 'V1Variation' is obsolete
warning CS0612: 'V1AdjustInventoryRequest' is obsolete

**Comment by StephenJosey** [comment]
Hi, as part of the 2.25 release, V1 Items API was deprecated. You should be using V2 Catalog API. See release notes here: https://github.com/square/connect-csharp-sdk/releases/tag/2.25.0

Note that even though it's deprecated, it isn't retired yet (but will be eventually, see here: https://developer.squareup.com/docs/build-basics/api-lifecycle#deprecated-apis), so it still is usable, and those are just warnings (shouldn't prevent your app from compiling).
