### ISSUE TITLE
Decline throwing exception

### ISSUE THREAD

**Issue by jslaybaugh** [square/connect-csharp-sdk#24]
My code looks like this (using 2.0.2.71 from nuget):

```
var api = new TransactionApi();
var response = api.Charge(options["AccessToken"].ToString(), options["LocationId"].ToString(), req);

if (response.Errors !=  null && response.Errors.Any())
{
	failureMessage = string.Join(", ", response.Errors.Select(x => string.Format("{0} {1}", x.Code.ToString(), x.Detail)));
}
else
{
	resultId = response.Transaction.Id;
}
```
as my understanding is that if I simply check for response.Errors then that will expose any errors and I can handle them there. Unfortunately, if I try to process a live transaction using a nonce created with a card of 4111 1111 1111 1111, instead of the decline coming back in response.Errors, the call to `api.Charge()` throws an exception and the Exception.Message is `Error calling Charge: {"errors":[{"category":"PAYMENT_METHOD_ERROR","code":"CARD_DECLINED","detail":"Card declined."}]}`.

So I'm forced to either parse the message property and deserialize that JSON or just write my own. I'm unable to find in the source where this might be a problem and I need something ASAP, so for the time being, I'm just going to make the REST calls myself, but if this could get fixed soon/easily, that would be awesome.

Thanks

**Comment by tristansokol** [comment]
Hello!

I'm not sure what you are asking to be "fixed". If you get a non-200 response (in this case a `402`), the SDK will throw an exception. Are you looking for the error message to be more easily parsed?

**Comment by jslaybaugh** [comment]
Well, to me it would be more easily consumable if even non-200 responses followed the same format and just populated the Errors property with the JSON that is just being output as a string in the message. Or another way I'd probably implement it is by subclassing `Exception` and throwing that... and there would be a property therein that enumerated the errors. That way as the consumer of the library I always know what I'm doing with the response whether it is positive or negative and I'm not having to parse apart the string to provide helpful feedback to the end-user.

**Comment by tristansokol** [comment]
Are you getting `Square.Connect.Client.ApiException`s? Are you able to parse out the `errorCode` or `ErrorContent` fields?

**Comment by jslaybaugh** [comment]
Ah, actually didn't know about that class. I just had a `catch (Exception ex)` and when I inspected it I didn't see it was an ApiException. When I replaced it with that, yes, I get more manageable JSON in the `ErrorContent` field and I can deserialize that for now.
