### ISSUE TITLE
Is it possible to breakdown the total charge amount ? 

### ISSUE THREAD

**Issue by andronachev** [square/connect-csharp-sdk#3]
Hi, 

Is it possible through the API, to breakdown the total charged amount? 
e.g. $ 100 = $70 product + $20 shipping + $10 tax ? so that it will show up accordingly in the Square Up Dashboard ? 

From the current API documentation, it does not seem to be possible. Is this planned to be implemented ? 

Regards

**Comment by ti55987** [comment]
Hi Vlad,
Thank you for asking! We are constantly working on improving our APIs and this is an addition that's on our roadmap. However, at this time we can't commit to a date yet. Please stay tune with us!
