### ISSUE TITLE
Calling Charge() on the Transaction API throws exception instead of returning response with error list

### ISSUE THREAD

**Issue by andronachev** [square/connect-csharp-sdk#36]
Hi,

I have the following code:

```
ChargeRequest body = new ChargeRequest(IdempotencyKey: idempotencyKey, 
                                                   AmountMoney: money,  
                                                   CardNonce: token, 
                                                   DelayCapture: _squarePaymentSettings.AuthorizeOnly, 
                                                   ReferenceId: processPaymentRequest.OrderGuid.ToString(), 
                                                   BillingAddress: billingAddress);

            var response = _transactionApi.Charge(_squarePaymentSettings.AccessToken, _squarePaymentSettings.LocationId, body);
            if (response.Errors == null || response.Errors.Count == 0)
            {
                   //.... al good
            }
            else
            {
                response.Errors.ForEach((e) => {
                    result.AddError(e.Detail);
                });
            }
```

and I just tested creating a charge with amount **403** , which according to the documentation (https://docs.connect.squareup.com/articles/using-sandbox ) should - and really does - result in the card being rejected. But instead of getting back the response object, with the Errors array, the transactionApi.Charge method throws an Exception, which is later caught in a catch block. 

The exception contians the following message: 

Error calling Charge: {"errors":[{"category":"PAYMENT_METHOD_ERROR","code":"CARD_DECLINED","detail":"Card declined."}]}

**Is this a bug, or is this behavior configurable within the SDK ?** 

This is v 1.0.0 I should add - quite old, I know

**Comment by mattanger** [comment]
I'm also interested in knowing a bit more about this. Initially, I expected these types of errors to be returned in the response, but found out, like @andronachev, that they were not.

What is the purpose of the Errors array?

**Comment by alecholmes** [comment]
Hi @andronachev and @mattanger. This is expected with the current and recent versions of the SDK. The contents errors array is transformed into the exception message for the SDKs, and is only directly available when making lower-level HTTP calls to our APIs directly.

In terms of how you're writing code, do you have preferences for how you would like to handle this type of error?

**Comment by mattanger** [comment]
Thanks for the response @alecholmes. I personally would prefer that the error messages be returned as part of the response. I don't think something like a declined card is "exceptional" enough of an error to cause an exception.

I think that the SDK is great overall, the only issue I have in regards to this is that when I was reading the documentation it isn't clear that exceptions are thrown for these types of errors which caused me a little bit of initial confusion.

**Comment by alecholmes** [comment]
That's very useful feedback! I'll pass it along to our team. Since the SDKs are autogenerated, we likely won't have any related changes in the short term.
