### ISSUE TITLE
ToCurrencyEnum  Example Outdated

### ISSUE THREAD

**Issue by ivansmith7795** [square/connect-csharp-sdk#44]
Just a heads up your ToCurrencyEnum usage in the example doesn't work:
Money money = new Money(amount, Money.ToCurrencyEnum(currency));

Should be:
Money money = new Money(amount, Money.CurrencyEnum.USD);

**Comment by tristansokol** [comment]
Just ran into this issue as well!

**Comment by StephenJosey** [comment]
Not sure what this is referring to any longer, closing out. Please reopen if this issue still exists with link(s).
