### ISSUE TITLE
Secure AccessToken . Good patterns.

### ISSUE THREAD

**Issue by kiquenet** [square/connect-csharp-sdk#47]
Any full source code real world sample for secure the AccessToken  ?

 public Example()
        {
            Configuration.Default.AccessToken = "YOUR_ACCESS_TOKEN";
        }

**Comment by alecholmes** [comment]
Great suggestion. We don't have a code sample yet. This is something that we've considered but we don't have a timeline yet for when we'd write sample code.

**Comment by StephenJosey** [comment]
Still no full example on this, nor do we provide guidelines on best practices around this. Generally it's up to the developer on how to secure their access tokens.
