### ISSUE TITLE
Web.config configuration

### ISSUE THREAD

**Issue by petespatio** [square/connect-csharp-sdk#5]
What is the proper way to configure the web.config so that i don't get the security exception when i load the page with the https://js.squareup.com/v2/paymentform?

Thanks in advance
Dave

Security Exception

Description: The application attempted to perform an operation not allowed by the security policy.  To grant this application the required permission please contact your system administrator or change the application's trust level in the configuration file. 

Exception Details: System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]
   System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet) +0
   System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark) +34
   System.Security.CodeAccessPermission.Demand() +46
   System.IO.Path.GetTempPath() +54
   Square.Connect.Client.Configuration..ctor(ApiClient apiClient, Dictionary`2 defaultHeader, String username, String password, String accessToken, Dictionary`2 apiKey, Dictionary`2 apiKeyPrefix, String tempFolderPath, String dateTimeFormat, Int32 timeout, String userAgent) +107
   Square.Connect.Client.Configuration..cctor() +64

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1087.0

**Comment by tristansokol** [comment]
Have you looked at the csharp example? 
https://github.com/square/connect-api-examples/blob/master/connect-examples/v2/csharp_payment/PaymentExample/web.config

**Comment by petespatio** [comment]
Thanks Tristan
Yes i did look at this example. This must have been developed and ran on a localhost. The web.config example doesn't have any security entries in the system.web section.

**Comment by bunnyc1986** [comment]
The stacktrack shows the exception was raised because it's trying to obtain system temp folder which is not necessary needed for our SDK.
The SDK is generated from swagger templates. So I filed an issue in the upstream template. Once we have decided solution, we will update the SDK code as soon as possible.

Thanks for reporting the issue.

**Comment by bunnyc1986** [comment]
@petespatio I have uploaded a new version to NuGet: https://www.nuget.org/packages/Square.Connect/2.0.2

Please try to update the SDK and see if it solves your problem.

**Comment by petespatio** [comment]
Thanks bunnyc1986
With this latest version, the example code doesn't seem to be operational.
The newMoney() uses the ToCurrencyEnum(). What has this been replaced with?

        Money amount = NewMoney(100, "USD");

        public static Money NewMoney(int amount, string currency)
        {
            return new Money(amount, Money.ToCurrencyEnum(currency));
        }

**Comment by bunnyc1986** [comment]
New you can create money like this:
```
Money amount = new Money(100, Money.CurrencyEnum.USD);
```
