### ISSUE TITLE
I have made a fork that is NetStandard 2.0 ... Very minimal changes

### ISSUE THREAD

**Issue by steevcoco** [square/connect-csharp-sdk#51]
Hi folks.

I case you are interested, I made a fork in NetStandard 2.0. I am working with the Api, and need NetStandard & Core compatibility.

The changes were simple: there is only one code change in the library:

ApiClient.PrepareRequest calls RestRequest.AddFile and it needs an additional argument.

There are just two other changes in tests, where Assert methods don't seem to exist.

Otherwise, the project files are completely new, and the solution file; and the NuGet management is changed into the project file and not packages.config. I did also replace the .gitignore file because it didn't ignore some .vs files.

Everything seems very straightforward, and I can make Api calls with success!

My fork is here:

https://github.com/steevcoco/connect-csharp-sdk

**Comment by MisterJames** [comment]
Nice work @steevcoco, but  If someone on the Square team could comment here it would be wonderful. 

`Swagger-codegen` has been updated to include .NET Standard, so you could add it to your build tools:

https://github.com/swagger-api/swagger-codegen#template-creator

**Comment by StephenJosey** [comment]
@steevcoco   the SDK has had many improvements recently - including supporting .net standard. Can you please try the latest version and let us know if you continue to experience any issues?

**Comment by steevcoco** [comment]
@StephenJosey My Api has actually migrated away from c# and so my use is on hold for the time being.

Thanks for the update.

I will close this issue. ... It never really was an "issue"!

**Comment by cabauman** [comment]
Hi @StephenJosey. Just as an FYI: I, too, have been using my own forked netstandard version. The latest official version installs into my netstandard2.0 project with the following errors (my Xamarin.iOS project references the netstandard lib):

![square error](https://user-images.githubusercontent.com/6819362/43685687-8514bf90-98f2-11e8-9067-1b1cc4581222.PNG)

Like steevcoco mentioned, it doesn't require any code changes except for a couple in the test project. With that said, may I ask what is holding the team back from switching over to netstandard2.0? I'm sure you guys have your reasons. Just curious.

**Comment by StephenJosey** [comment]
@cabauman thanks for the feedback! We are actually currently working on this, but we're deciding between a few different directions. We'll definitely let you know when it's been pushed out. Please let us know if you have any further feedback, though, it definitely helps out! 👍

**Comment by cabauman** [comment]
Glad it helps. Thanks to you and the rest of the team for all the great updates.
