### ISSUE TITLE
 Modify the sdk to work with .net core

### ISSUE THREAD

**Issue by JonathanUzcateguiG** [square/connect-csharp-sdk#57]
I am developing in .net core and the sdk does not work at the moment, locally download the code and modify it I want to upload my changes to contribute to the community.

my code is already working, I guess we should create a new branch

**Comment by GoogleBot42** [comment]
I encountered this issue as well.  The readme says that there is support mac and linux but only .net core support those platforms so there actually is support for dotnet core.  Recently, the build must have been broken.

**Comment by GoogleBot42** [comment]
This line is the issue:
https://github.com/square/connect-csharp-sdk/blob/master/src/Square.Connect/Client/ApiClient.cs#L135
.Net core (for whatever reason) isn't converting `System.Action<System.IO.Stream>` to a `byte[]` There may be other issues as well but I haven't encountered any.

**Comment by StephenJosey** [comment]
@GoogleBot42 @JonathanUzcateguiG  the SDK has had many improvements recently - including supporting .net core. Can you please try the latest version and let us know if you continue to experience any issues?

**Comment by raboud** [comment]
@StephenJosey the nuget package only shows v4.5 support not .net core 2

**Comment by raboud** [comment]
@StephenJosey but when you do you get a warning...yes it works but by just adding the packaging for .net core 2 or .net standard 2 you would remove the warning and people will not question whether or not there are issues.

**Comment by StephenJosey** [comment]
@raboud I see what you mean, and I agree. I don't have a timeline on when this might be completed, but we appreciate this great feedback. Thank you!

**Comment by raboud** [comment]
@StephenJosey if I get a chance a may do a pull request. BTW thank you for the package and your hard work.

**Comment by StephenJosey** [comment]
Hey everyone! Happy to announce that our C# SDK now targets .net standard 2.0. Please retrieve the latest version (from today!), and let us know if you run into any issues with core/standard, now.

Thank you all for being patient while we worked on this 👍 !
