### ISSUE TITLE
 when you create an item you can not pass the category_id

### ISSUE THREAD

**Issue by JonathanUzcateguiG** [square/connect-csharp-sdk#58]
the documentation indicates that you have the category_id attribute, but the library does not currently have this attribute.
![image](https://user-images.githubusercontent.com/28911069/38688073-31963ed6-3e46-11e8-9dee-d477e6bbcbe1.png)

this works in postman. 
I have this modification running and tested and I want to upload it to the repository

![image](https://user-images.githubusercontent.com/28911069/38688179-7bc5321e-3e46-11e8-8841-c1083a45f00d.png)

**Comment by frojasg** [comment]
Hi @JonathanUzcateguiG 

Thanks for reporting this issue. I will try to fix this bug as soon as possible.

**Comment by StephenJosey** [comment]
@JonathanUzcateguiG this has since been resolved. Please let us know if you find any other issues. Thanks!
