### ISSUE TITLE
V1 Timecard response incomplete

### ISSUE THREAD

**Issue by AppPackLtd** [square/connect-csharp-sdk#59]
The endpoint for V1 Timecard has fields that are not currently returned by the SDK (eg overtime_seconds_worked). From investigation it looks like these fields are related to the payroll system which is currently only available in the US?

https://docs.connect.squareup.com/api/connect/v1#datatype-timecard

**Comment by sseaman** [comment]
Should have been resolved some time ago. If not, please reopen.
