### ISSUE TITLE
v1ItemsApi batchtoken issue

### ISSUE THREAD

**Issue by ramprudvi** [square/connect-csharp-sdk#63]
getting only 1000 products out of  3000 items which is queried result of v2 api  
language: C#

**Comment by StephenJosey** [comment]
Hi @ramprudvi, there's a undocumented function that provides the `batch_token` in the response. See the code here: https://github.com/square/connect-php-sdk/blob/4756e538e3ec2179349b8ed059173e1cc7b32630/lib/Api/V1TransactionsApi.php but essentially it is the function called `listPaymentsWithHttpInfo`.

If this is not the issue you're referring to, can you please reach out to us via developers@help-messaging.squareup.com so we can work with you to resolve this?

**Comment by StephenJosey** [comment]
Hi @ramprudvi there is an undocumented function called `ListItemsWithHttpInfo` (see here for info: https://github.com/square/connect-csharp-sdk/blob/master/src/Square.Connect/Api/V1ItemsApi.cs), that includes the `batch_token` in the response.

If that doesn't resolve your question, can you please reach out to us via developers@help-messaging.squareup.com so we can work with you to resolve this?

**Comment by ramprudvi** [comment]
Hi,
the exact issue is i am using v1itemAPI to get List items but unable to
entire list even i pass parameters only 1000 items are retrieved and
batch_token cursor is returned as blank
Can you please specify more on this issue.

thanks & regards,
ramaprudvi akula

**Comment by StephenJosey** [comment]
@ramprudvi were you able to resolve this issue? I saw you had emailed in, but just wanted to make sure it got cleared up. Please let me know if there's any further issues. Thanks!
