### ISSUE TITLE
ModifierLists for Item always null

### ISSUE THREAD

**Issue by DanielGlos** [square/connect-csharp-sdk#72]
Hello,
I'm trying to retrieve ModifiersLists for item but its still null althought they are set in Square app and assigned to the item. I'm able to get them with "itemsApi.ListModifierLists(squareLocationId)" call but shouldn't they be also retrieved with item when I do "itemsApi.ListItems(squareLocationId)" call ?

**Comment by StephenJosey** [comment]
@DanielGlos thanks for bringing that up! It seems like it should, so I'll follow-up shortly. In the mean time, could you try using our V2 `ListCatalog` instead, and see if that works for you?

https://github.com/square/connect-csharp-sdk/blob/master/docs/CatalogApi.md#listcatalog

**Comment by StephenJosey** [comment]
@DanielGlos Our documentation says that ListItems returns an array of Items and "These objects do not include modifier_lists or fees fields. To get an item's associated modifier lists and fees, use the Retrieve Item endpoint." 

Alternatively, you can use our V2 `ListCatalog` endpoint which does include the modifiers: https://github.com/square/connect-csharp-sdk/blob/master/docs/CatalogApi.md#listcatalog

**Comment by DanielGlos** [comment]
Hi,
Thank you for your quick response and I'm sorry. Didn't noticed the
description that it indeed shouldn't load also modifiers

Dňa pi 27. 7. 2018, 17:44 Stephen Josey <notifications@github.com>
napísal(a):

**Comment by StephenJosey** [comment]
No worries! I also forgot to point out where it is, sorry about that. See the documentation here: https://docs.connect.squareup.com/api/connect/v1#get-items

Of course, please let me know if you have additional questions or concerns! We definitely appreciate developers catching issues 👍 .
