### ISSUE TITLE
Card nonce

### ISSUE THREAD

**Issue by DanielGlos** [square/connect-csharp-sdk#76]
Are there any possibilities obtaining card nonce another way then through sqpaymentform? We are developing native iOS application and want to provide Apple pay and standard card payments.

**Comment by StephenJosey** [comment]
At this time, the only way to generate a card nonce is via the `SqPaymentForm`. We do have our [POS API](https://docs.connect.squareup.com/payments/pos/overview) and [Reader SDK](https://docs.connect.squareup.com/payments/readersdk/overview) for iOS applications, but both are meant for in-person payments. If you want to take online payments, your best option right now is to create a mobile-friendly website.
