### ISSUE TITLE
Need up to date version of RestSharp

### ISSUE THREAD

**Issue by sheam** [square/connect-csharp-sdk#81]
I get a lot of warning in my build because other packages use up to date versions of RestSharp. But Square doesn't work with recent versions of RestSharp.

**Comment by sheam** [comment]
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void RestSharp.RestRequest..ctor(System.String, RestSharp.Method)'.

**Comment by sheam** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  You an download my fork.                                                                                                                                                                        ~Shea M                                                                                                                                                                           From: notifications@github.comSent: November 18, 2018 9:26 PMTo: connect-csharp-sdk@noreply.github.comReply to: reply@reply.github.comCc: shea.martin@gmail.com; author@noreply.github.comSubject: Re: [square/connect-csharp-sdk] Need up to date version of RestSharp (#81)  I am having the same issue. Is there a fix for this?

**Comment by StephenJosey** [comment]
The latest version of the C# SDK works with the latest version of RestSharp. If you're not able to use 2.10.2 or later then you will need to use the fork that @sheam provided.

**Comment by RobertAba** [comment]
Thank you for the update. Were you able to recreate the problem or would you like some source code and screen shots?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gtwilliams03** [comment]
I updated our app to the latest versions of Square Connect and RestSharp and couldn't figure out why everything broke until I found this thread.  Any update on when Square and RestSharp will play nice?

**Comment by cppmyjob** [comment]
Do you plan to update your SDK to the latest version of RestSharp?

**Comment by StephenJosey** [comment]
Hi all - we've migrated to a new .NET SDK: https://github.com/square/square-dotnet-sdk. This should work better for you all, but please let us know in the new repo if you do experience any issues. Thanks!
