### ISSUE TITLE
Issue Updating Square.Connect

### ISSUE THREAD

**Issue by Telarin** [square/connect-csharp-sdk#82]
Receiving the following error when attempting to update the NuGet package from v2.9.0.279 to v2.11.0, dependencies all appear to be met (RestSharp and NewtonSoft.Json updated to most current version and .Net version of project higher than minimum listed):

Could not install package 'Square.Connect 2.11.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by StephenJosey** [comment]
In order to use .NET Core 2.0, your project will need to be using .NET Framework 4.6.1. Otherwise, you will need to use Square.Connect version 2.10.1 or below to work with older frameworks. Please let me know if you have additional questions!
